version: '3.9'
services:
  # ESLint
  eslint:
      container_name: eslint
      build:
        context: .
        dockerfile: Dockerfile
      image: eslint:1.0
      volumes:
          - .:/home/app
          - /home/app/node_modules
      working_dir: /home/app
      command: tail -F anything